### ISSUE TITLE
Stay on top mode for undocked dfl window

### ISSUE THREAD

**Issue by metude** [operasoftware/dragonfly#112]
I need to stay on top mode for dfl. I use DFL with undocked sometimes but it's very hard to manage it every time when I click an item in page.

**Comment by hzr** [comment]
This is not something that can be fixed in Opera Dragonfly. It has more to do with your window manager (I have the option "Always on Top" in Metacity for example). This would be a feature request for the browser itself, where it might be fixable.

**Comment by p01** [comment]
Good feature request, wrong place ;) I filed a bug on the Desktop browser. Let's see how it goes

**Comment by metude** [comment]
@hzr Where will I post feature requests?

@p01 Thanks.

**Comment by hzr** [comment]
@metude, they can be posted in http://my.opera.com/community/forums/forum.dml?id=24, but there is no reason to do so now that p01 did it. :)
