### ISSUE TITLE
Firefox 19 throws  error about redeclaration of const k

### ISSUE THREAD

**Issue by c69** [operasoftware/dragonfly#124]
Both Opera and Chrome render standalone DF ok (with "waiting for connection on port 0" message) 
https://dragonfly.opera.com/app/stp-1/client-en.xml

But Firefox 19 throws error. This is probably very minor issue, but anyway ..

"TypeError: redeclaration of const k"

**Comment by hzr** [comment]
This is known and has been fixed on the https://github.com/operasoftware/dragonfly/tree/chrome-firefox-support branch. Note that the "support" here means running it via dragonkeeper.

Thanks.
