### ISSUE TITLE
Resource inspector: attempt to guess resources type

### ISSUE THREAD

**Issue by c69** [operasoftware/dragonfly#126]
When server sucks and does not send content-type or mime-type headers, Dragonfly shows simple resources like .png, .jsp, or even .html as 'unknown' and thus - it does not preview them in 'Resources' tab.

This is very inconvenient.

Would have been nice, if resource inspector tried to sniff / guess resource type - especially when there is an extension (and its safe - no need to "preview .EXE files").

Algorythm:
- IF extension is PNG, JPG, GIF, WEBP - try to decode as image 
- IF extension is CSS, JS, JSON - try to render as style or script file
- IF extension is XML or RSS - try to render as xml with default styling
- IF extension is HTML, HTML, PHP, JSP, PL - try to render as html
- IF extension is MD, TXT - try to render as ascii or utf8 plain text
- ELSE unknown type, just like it is now. But with a button - "preview as plain text" which can give a simplest preview (anything would be better than current "no information available")

**Comment by p01** [comment]
I've got the feeling you will like what's in the Cutting-edge channel of Dragonfly ;)
The new Resource Inspector needs a bit more testing but it should soon land on master/stable.
