### ISSUE TITLE
Ability to dock Dragonfly to the left or right of Opera window  

### ISSUE THREAD

**Issue by samkatakouzinos** [operasoftware/dragonfly#131]
Currently I am unable to (find out how to) dock Dragonfly to the left or right of the Opera window. 

Is this possible today? 
If not, may you consider this as a possibility? 

Sam Katakouzinos

**Comment by hzr** [comment]
This is unfortunately not possible currently. We have a feature request for it internally.

**Comment by mosalski** [comment]
Any progress with this?
