### ISSUE TITLE
Suggestion: Visual/UX : Resource panel formatting

### ISSUE THREAD

**Issue by Denyerec** [operasoftware/dragonfly#133]
Suggestion to reduce padding on resource view list items. Current view results in a lot of scrolling once subitems "Scripts", "Images" etc are expanded.

**Comment by p01** [comment]
The styling and padding of the new Resource Inspector — currently available on Cutting Edge — are consistent with the Network view. But you're right, it is a bit too much for this very view. I will adjust the padding, and try to find a pleasant balance between the nodes ( featuring a 16×16 icon ) and leaves ( resources ) of the tree.

**Comment by p01** [comment]
Fixed in https://github.com/operasoftware/dragonfly/commit/e94b242a1c41b272f3c5f54072ac190d3a95af33

**Comment by Denyerec** [comment]
Great!
