### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by metude** [operasoftware/dragonfly#135]
I couldn't able to name it sorry for title.

To reproduce bug try these steps:
1. Go to a facebook message conversation. Something like this https://www.facebook.com/messages/22255556666999
2. Now open DFL and type this to console.
   `document.getElementsByName("attachment[]");`
3. Click + icon beside of `NodeListPrototype`
4. Click + icon beside of `1 HTMLInputElemtn`
   Now you should got bug
   ![DFL bug](http://i.imgur.com/1NfRR.png)

My DFL version: http://prntscr.com/jvepd

**Comment by hzr** [comment]
Thanks for the report. The bug is in Opera Core. We had a similar bug a while ago that was fixed, bug I don't think anu released version of Opera has it.

Closing as it's not a Dragonfly bug.
