### ISSUE TITLE
Opening Dragonfly on the second Opera Window

### ISSUE THREAD

**Issue by greench** [operasoftware/dragonfly#141]
If you have opened Dragonfly on the first Opera window, you cannot open it for second window. If you try to this, Opera is always opened on the first windows with content of tab on the second window.
1. Start opera.
2. Open a web page.
3. Open dragonfly
4. Ctrl + n to open new window
5. Open a tab in the second window
6. Open dragonfly for this second window
7. The first window will be focused on.

**Comment by p01** [comment]
Yes this behavior feels weird. It makes sense but I doubt that's what the majority expects.
I just filed a Desktop bug for this. Next time you see something odd that clearly feels out of reach of the client side of Dragonfly, don't hesitate to file a [Bug report on the Desktop browser](https://bugs.opera.com/wizarddesktop/).
