### ISSUE TITLE
Calculation Bug?

### ISSUE THREAD

**Issue by metude** [operasoftware/dragonfly#148]
In Dragonfly these are returns as
    var i = 0;
    console.log(i++); // 0
    console.log(++i); // 2
    console.log(i--); // 2
    console.log(--i); //0

But in real life

```
var i = 0;
i++;
alert(i); // 1
++i;
alert(i); // 2
i--;
alert(i); // 1
--i;
alert(i); // 0
```

Is there something that I miss? Why diffrent values in console.log?

**Comment by metude** [comment]
OK. I got it now, looks like I need some sleep.

**Comment by metude** [comment]
OK I got it, looks like i need some sleep.

**Comment by p01** [comment]
What you see in Dragonfly' console is correct as you can you by yourself when doing:

```
var i = 0;
alert( [ i++, ++i, i--, --i ] );
```

The post-increment and pre-increment operators are named so for a reason ;)

NB: Watch out! I can see the shadow of @douglascrockford growing behind you as I type.
