### ISSUE TITLE
Show line numbers in Documents-View

### ISSUE THREAD

**Issue by bommelmuetz** [operasoftware/dragonfly#149]
It would be nice to show the line number in the documents view of draonfly just like it is done in source code view. This would speed up locating elements in source code.

**Comment by danfooo** [comment]
This will only work when your markup is formatted exactly like we format the DOM view in Dragonfly. The DOM view shows a snapshot of the current DOM, that is often something different than the initial markup, and it's formatted differently too. What you're looking for is probably in the Markup section in Resources.
