### ISSUE TITLE
Fixed position elements do not resize after closing 'docked' dragonfly

### ISSUE THREAD

**Issue by mrak** [operasoftware/dragonfly#151]
### 1. Create the following `test.html` page:

``` html
<!doctype html>
<html>
   <head></head>
   <body>
      <div style="
         position: fixed;
         top: 0;
         right: 0;
         bottom: 0;
         left: 0;
         background: black;"></div>
   </body>
</html>
```
## Expected Result

An entirely black page
## Observed Result

The portion of the page covered by dragonfly in docked mode is white, the rest is black
## Environment

Protocol Version: 1
Core Version: 2.12.388
Operating System: MacIntel
Platform: MacIntel
User Agent: Opera/9.80 (Macintosh; Intel Mac OS X 10.8.2) Presto/2.12.388 Version/12.12
Opera Dragonfly Version: Opera Dragonfly 1.2012.12.14.1
Revision Number: 2012.12.14:4d106476132f, default, Opera_Dragonfly_1.2012.12.14.1_Release_task_18_DFL-3735

**Comment by hzr** [comment]
Hi and thanks for the report. This bug is in Opera core, and is not related to Dragonfly. We have an issue filed internally for this bug, so I'm closing this.

**Comment by mrak** [comment]
Glad it's covered! Sorry for the duplicate then :P
