### ISSUE TITLE
useful 

### ISSUE THREAD

**Issue by gvmir** [operasoftware/dragonfly#164]
I found the closed tabs list feature, in the toolbar from opera 12, very useful. I can't seam to find something similar in opera 16.
I would appreciate if we could have that feature again.
Thank you!

**Comment by p01** [comment]
Huh... have you looked at the Opera menu ? There is a submenu called "Recently closed" ;)

Anyways, this is the repository for Opera's Dragonfly Developer tools.
Feedback about Opera's Desktop browser is better sent to the [Desktop Team's blog](http://my.opera.com/desktopteam/blog/) or the [Opera forum](http://my.opera.com/community/forums/tgr.dml?id=2). 

Hope that helps,
