### ISSUE TITLE
What happened to favorites?

### ISSUE THREAD

**Issue by zincfinger** [operasoftware/dragonfly#165]
What happened to the favorites facility. It was something that many of us were familiar with and was easy to use but now you've removed it and I assume replaced it with something that I cannot figure out at all. I have tried! You failed to anticipate that people would obviously ask about it. (Its not in your help page)
What ever you replaced it with is not intuitively obvious to use. not to me anyway.
Sorry Opera. I like you but you really screwed this one up.

**Comment by p01** [comment]
I see you are a bit confused indeed. This is the repository for Opera's Dragonfly Developer tools.

Feedback about Opera's Desktop browser is better sent to the [Desktop Team's blog](http://my.opera.com/desktopteam/blog/) or the [Opera forum](http://my.opera.com/community/forums/tgr.dml?id=2). 

Hope that helps,
