### ISSUE TITLE
Opera 12 and the big problem with youtube

### ISSUE THREAD

**Issue by Bojan1302** [operasoftware/dragonfly#166]
First off,,I tried everything ! When i go to youtube i can not play videos or hear.It says always you need to download the flashplayer which i had about 50 times,and i restart Opera and again the same problem ! But not only in youtube....I can not watch videos online with Opera 12 anywhere. I don't get it. How to fix this ?!?

**Comment by p01** [comment]
It sounds like, somehow, you have disabled plugins in Opera 12. Trying pressing F12 or going to Opera Menu > Settings > Quick Preferences, and make sure plugins are enabled.

Hope that helps,
Either way this is definitely not a Dragonfly issue :p

**Comment by chriskr** [comment]
Also you could try a newer Opera version: http://www.opera.com

**Comment by Bojan1302** [comment]
Again the same problem ! on the screen it say: you need to install adobe-flash player or HTML 5,click more to find out about HTML browser. MY OS is Windows 7 64 ,not the ordinary 32. And I have precisely downloaded Opera12 for a 64bit Windows 7. I tried all above you have told me but nothing...always the same message and problem. But on the older versions of Opera everything worked perfectly and fast. I am frustrated.what is the problem? Opera is my favorite browser and easy to use and fast...and I don't want to change it and go on Firefox,explorer or chrome.

**Comment by p01** [comment]
This repository is not Opera's help desk but let's try one last time.

Try disabling all your extensions, and make sure you didn't check "Enable On Demand Plugin" in opera:config#UserPrefs|EnableOnDemandPlugin

Whether this works or not, I strongly recommend you to upgrade to a newer version of Opera unless you REALLY know what you are doing. Opera 12 is getting old and the world wild web is moving fast!

**Comment by Gregory234** [comment]
I am not sure if we using the same Opera versions but I had the same problem with Opera especially with Flash player and opening YouTube videos or Flash games. I find out that solution is actually very simple in my case I had Opera Turbo turned on. Maybe this tutorial will help you to fix the problem : http://pc-problem-solutions.blogspot.com/2014/11/click-to-run-youtube-video-opera-problem.html
