### ISSUE TITLE
opera browser using matrox TrippleHead2Go Digital Edition

### ISSUE THREAD

**Issue by dutchy12345** [operasoftware/dragonfly#169]
Opera has problems when using the TrippleHead2Go Digital Edition. Seems  to be the same problem Google Chrome has also. At some point the browser will not start up any more. It tries to start 3 times in a row but crashes finally. What to do? Thanks

**Comment by p01** [comment]
Thanks for the feedback. Unfortunately this is the repository of the Opera Dragonfly, the developer tool of the Presto based versions of Opera Desktop. Please use the [bug report wizard for Opera Desktop](https://bugs.opera.com/wizarddesktop/), as I believe you are talking about the Opera Desktop.
