### ISSUE TITLE
some old features wanted back

### ISSUE THREAD

**Issue by chiragdkothari** [operasoftware/dragonfly#171]
pls bring back the turbo option istead of the off road mode.
also add an option to choose between wap and normal browsing so that the user doesnt not need to look for wap pages instead the browser will automatically load only wap pages once the user choose the wap option

**Comment by p01** [comment]
Thanks for the feedback. Unfortunately this is the repository of the Opera Dragonfly, the developer tool of the Presto based versions of Opera Desktop.  believe you are talking about the Opera for Mobile phones of which there are many versions too. The easiest might be use the [bug report wizard for Opera Desktop](https://bugs.opera.com/wizarddesktop/) as it is the easiest for external reporters, and make sure to specify which version of the browser, the platform, OS, etc...
