### ISSUE TITLE
Green background on non selected elements

### ISSUE THREAD

**Issue by danielocdh** [operasoftware/dragonfly#172]
Since like 2 months ago I've been having a green highlight of elements I select after I move to another element. I don't know if this change was intentional but I don't see any place to remove that green highlight or configure it.

Please let me know how to do it, or where I can get a version of the most recent developer tools without that green crap.

**Comment by chriskr** [comment]
I assume you are talking about the highlight of elements with Dragonfly. Go to settings, the cog wheel in the top right corner, to the 'Documents' tab, at the bottom you find 'Element highlight', and there is 'Reset default color'.

**Comment by danielocdh** [comment]
Thank you for your answer chriskr, and sorry for the delay in mine.

Here is a picture that explains better how to reproduce my issue. Let me know if I should create a video to show it better.

http://i57.tinypic.com/281tz5u.jpg

On the screenshot the green square is not really a problem, but many times when developing elements inside elements or elements with different background colors, having the green background on all previously "inspected" elements is really bad.

**Comment by chriskr** [comment]
Ok, looks like you have enabled "Keep elements highlighted". You can turn it off in the context menu (right click menu) of the DOM view.

**Comment by danielocdh** [comment]
Thanks a lot, I read the options many times but I guess I didn't see it, my bad.
