### ISSUE TITLE
Save as PDF option when Print 

### ISSUE THREAD

**Issue by MidhunChowdary** [operasoftware/dragonfly#175]
Hi ,

I use both opera and chrome. I see the feature of saving the pdf is missing in opera.
In chrome you get an option as you can save a webpage in local destination i.e save as pdf in additional to the Fax and printers.

**Comment by p01** [comment]
This is the repository of the decommissioned Opera 12' developer tool: Dragonfly.
Please use the **[wizard](https://bugs.opera.com/wizarddesktop/)** to report bugs and feature requests for Opera for Computer.
