### ISSUE TITLE
missing features?

### ISSUE THREAD

**Issue by unclenatron** [operasoftware/dragonfly#176]
Since the new update, I seem to be missing the zoom tab that was previously on the bottom-right, and the ability to move my tabs bar to the bottom of the screen.  Also, I cannot remove the text from the tabs or opt for the icon-only view of the last version.  Now this program is Firefox, except firefox displays correct colors.

**Comment by chriskr** [comment]
Ok.

**Comment by p01** [comment]
I'm afraid you are confused. This repository is about Dragonfly, Opera's former Developer Tools.
You seem to be talking about Opera for Desktop itself. Check out the [help pages](http://www.opera.com/help/computer).

If anything the new Opera for Desktop can actually handle today's Web, something that unfortunately wasn't exactly the case of the previous incarnations of Opera for Desktop.
