### ISSUE TITLE
I can't see remote debug button in the dragonfly

### ISSUE THREAD

**Issue by SinjinJang** [operasoftware/dragonfly#178]
I want to debug a web page remotely, so I read below document.
http://www.opera.com/dragonfly/documentation/remote/
In Stage 2, however, I can't find the remote debug button on my Opera browser.
Do I have to do some configuration to active remote debug in Opera, or need to install something more?

![opera_no_remote_debug_button_in_dragonfly](https://cloud.githubusercontent.com/assets/4989522/9320183/df63b904-4591-11e5-8093-afc55bf67517.png)

I just installed Opera browser (v31.0 latest stable version) which downloaded from Opera official download page on my Windows 7 PC...

Thanks in advance.

**Comment by lmormol** [comment]
You can find Dragonfly only in versions based on Presto engine (latest: 12.17).

**Comment by SinjinJang** [comment]
Oh I see, I downgraded Opera to v12.16, and now I can see Remote debugging button. Many thanks :-)
