### ISSUE TITLE
real problem

### ISSUE THREAD

**Issue by srostami69** [operasoftware/dragonfly#179]
it was my first time and the last time that installed opera in windows 10 
when i installed opera all things were good but after 5 minutes it hangs and exit again i open it this tim after 1 minute and i reinstalled it and agaion hang in ver. 34 i surprised now who use this funny browser

**Comment by chriskr** [comment]
You are on a very wrong place to report issues with the Opera browser. If you like to do that use https://bugs.opera.com/wizarddesktop/
