### ISSUE TITLE
Droped suport -o- prefixes on opera 12.50

### ISSUE THREAD

**Issue by welitonfreitas** [operasoftware/dragonfly#36]
the new build 1538 opera 12.50 has droped suporte for -o- prefixes  from Transitions, Animations and Transforms implementation. Dragonfly use this prefixes on any stylesheet. I prepared a commit removing those prefixes, where branch i send the pull request?

**Comment by hzr** [comment]
Thanks a lot! This has already been fixed on the [bugfixes branch](https://github.com/operasoftware/dragonfly/tree/bugfixes) however, and will be integrated soon.
