### ISSUE TITLE
Cannot see user JS or injected scripts

### ISSUE THREAD

**Issue by joelspadin** [operasoftware/dragonfly#38]
The dropdown to select a script displays all the scripts on the page, but all user scripts and scripts injected by extensions are missing. 

[Here is a screenshot.](http://files.myopera.com/spadija/albums/2241911/dragonfly%20missing%20scripts.png) This happens on every page on the stable, cutting-edge and experimental versions of Dragonfly. I am running Opera 12.01 x64 on Windows 7, and this also occurs in Opera Next x64 build 1546.

**Comment by hzr** [comment]
Thanks, this is known and has been fixed. We will have a fix out shortly.

**Comment by hzr** [comment]
Fixed with https://github.com/operasoftware/dragonfly/commit/c66020b531db4b78b9760037fad685882855a000.
