### ISSUE TITLE
Date Is Not Displayed In Inspection

### ISSUE THREAD

**Issue by opticyclic** [operasoftware/dragonfly#49]
Dates are not displayed in inspection.
Debug the following script in Dragonfly and Firebug and see the difference.

``` html
<!DOCTYPE html>
<html>
<body>

<script>

var d=new Date();
document.write(d);

var i;
var mycars = new Array();
mycars[0] = "Saab";
mycars[1] = "Volvo";
mycars[2] = "BMW";

for (i=0;i<mycars.length;i++)
{
document.write(mycars[i] + "<br />");
}
</script>

</body>
</html>
```

Notice how Dragonfly shows a list of confusing info:
![Dragonfly](http://s9.postimage.org/d66vuv6en/dragonfly.png)

But Firebug shows the actual date:
![Firebug](http://s18.postimage.org/7jzfgdjl5/firebug.png)

**Comment by hzr** [comment]
For objects, we only show the "class" name next to the property name. We've chosen not to print a representation of the object. While this can sometimes be useful, it quickly leads to a lot of clutter. You can however hover the "class" name (in this case "Date") to get the .toString() representation of it.

The confusing info you're referring to is essential when debugging and is something that we need to show. :)

**Comment by opticyclic** [comment]
We have 2 use cases here then:
1) When you need all the extra info about the object
2) When you just want a simpler high level view of the object

To cover both use cases, how about an option that allows you to toggle between the current view and a simple view.

**Comment by hzr** [comment]
A setting is unlikely to happen as we're trying to simplify them and remove a lot of them. But the extra information is easily accessible from the tooltip when you need it.

If you need to check the toString value of the date on each step for example, you can add a watch with `<date>.toString()`.
