### ISSUE TITLE
populate form

### ISSUE THREAD

**Issue by oddshoes** [operasoftware/dragonfly#57]
I develop bespoke net based databases for small businesses. I have recently advised/compelled all my clients to switch to Opera because of the better HTML5 compliance.  One question on my own behalf as a developer, is there a "populate form" feature in Dragonfly? as I work on quite large form submission and use this facility in Firebug quite frequently.

**Comment by hzr** [comment]
There is no such feature, no. How do I try this in Firebug?

**Comment by oddshoes** [comment]
Its in the firefox (firebug?) developers menu toolbar Forms->populate form fields. 

cheers
