### ISSUE TITLE
Dragonfly Doc Error

### ISSUE THREAD

**Issue by ArtKns** [operasoftware/dragonfly#58]
On doc page http://www.opera.com/dragonfly/documentation/
Windows ... Edit → Developer Tools → Opera Dragonfly 
should be:  View → Developer Tools → Opera Dragonfly

Also, the content is not date stamped. 
Any content worth posting needs to be dated.

**Comment by hzr** [comment]
Thanks for the report.

Could you post the same thing at https://github.com/operasoftware/dragonfly-documentation/issues (and then possibly close this)?

Thanks in advance!

**Comment by ArtKns** [comment]
Transfered to operasoftware  / dragonfly-documentation

https://github.com/operasoftware/dragonfly-documentation/issues/6
