### ISSUE TITLE
More visible Ev pop-up

### ISSUE THREAD

**Issue by greench** [operasoftware/dragonfly#59]
If you click ev button on DOM screen, a pop-up will be opened. As you can see, many events can be assigned to one element. I cannot see the top of the list because height resolution of the screen is insufficient to display whole list. I wish to use wheel of the mouse to scroll around the list if the mouse cursor is over the pop-up.
![Many events are attached to an element](http://img705.imageshack.us/img705/4377/menu004t.png)

Protocol Version: 1
Core Version: 2.12.378
Operating System: Linux
Platform: Linux
User Agent: Opera/9.80 (X11; Linux x86_64; Edition Next) Presto/2.12.378 Version/12.50
Opera Dragonfly Version: Opera Dragonfly 1.2012.08.23.1
Revision Number: 2012.08.23:6836bb2733e2, experimental, HEAD

**Comment by hzr** [comment]
Thanks for the report, we'll look into it.

**Comment by p01** [comment]
For the record this issue was addressed and a fix was released on the stable path in the build:

Opera Dragonfly Version: Opera Dragonfly 1.2012.10.03.1 
Revision Number: 2012.10.03:5f727ef7abb8, default, Opera_Dragonfly_1.2012.10.03.1_Release_task_15_DFL-3628
