### ISSUE TITLE
Reformat code on Scripts tab

### ISSUE THREAD

**Issue by metude** [operasoftware/dragonfly#79]
Could you add reformat code option to resources and scripts tab?

**Comment by hzr** [comment]
There's a setting for it in Scripts provided you have a new enough Opera version. Try the latest 12.10 snapshot.

**Comment by metude** [comment]
This is what I'm talking about. Thanks.

Is there word wrap feature?

**Comment by p01** [comment]
If you mean word wrapping of the Scripts ( and other text resources ), it is in the pipeline. Can't promise an ETA.

**Comment by metude** [comment]
Yes. No need to promise just a guess for ETA would be nice.
