### ISSUE TITLE
Dragonfly not working with opera 11.50 anymore

### ISSUE THREAD

**Issue by lemonsqueeze** [operasoftware/dragonfly#93]
Hiya,
Not sure if dragonfly is supposed to support older versions of opera,
but fyi dragonfly doesn't work in opera 11.50 anymore (linux version).

Dragonfly loads forever, and error console reports css errors and a js syntax error (see below)

**Comment by lemonsqueeze** [comment]
[many more css errors]
...
[10/01/2012 03:32:46 PM] CSS - https://dragonfly.opera.com/app/stp-1/style/dragonfly.css
Linked-in stylesheet
Unrecognized function
Line 8172:  
                                      rgba(255, 255, 255, 0.25) 100%);
  --------------------------------------------------------------------^
[10/01/2012 03:32:46 PM] CSS - https://dragonfly.opera.com/app/stp-1/style/dragonfly.css
Linked-in stylesheet
Invalid value for property: background-image
Line 8172:  
                                      rgba(255, 255, 255, 0.25) 100%);
  --------------------------------------------------------------------^
[10/01/2012 03:32:46 PM] JavaScript - https://dragonfly.opera.com/app/stp-1/script/dragonfly-en.js
Linked script compilation
Syntax error at line 21 while loading:
._dict[a+b]=c};this.delete=function(b){d
--------------------^
expected identifier, got keyword 'delete'

**Comment by hzr** [comment]
Thanks, this will be fixed in the next release.

**Comment by lemonsqueeze** [comment]
I checked out and built dragonfly from git, now running from local copy 
(as in http://www.opera.com/dragonfly/documentation/products/)
This version works (haven't tried later ones so far)
  Opera_Dragonfly_1.2012.08.13.3_Release_task_12_DFL-3443

**Comment by lemonsqueeze** [comment]
Wow, that was fast =)
